#!/bin/bash
#PBS -N no_gap_at_cluster_conda
#PBS -A GT-lj2
#PBS -l nodes=1:ppn=1
#PBS -l pmem=16gb
#PBS -l walltime=20:00:00
#PBS -q inferno
#PBS -j oe
#PBS -o at_cluster_conda.out


cd $PBS_O_WORKDIR
echo "Started on `/bin~C/hostname`"

module load abaqus/2020

module load anaconda3/2020.11
conda activate wave_env_cl

conda info

abaqus cae noGUI=create_model_script_v15_no_gap.py

# python3 run_automated_simulations_cluster.py