#!/bin/bash
#PBS -A GT-lj2
#PBS -N run_parallel_on_cluster
#PBS -l nodes=1:ppn=1
#PBS -l pmem=16gb
#PBS -l walltime=35:00:00
#PBS -q inferno
#PBS -j oe
#PBS -o run_parallel_on_cluster.out


cd $PBS_O_WORKDIR
echo "Started on `/bin~C/hostname`"

echo "P_SET = $P_SET"

module load abaqus/2020

module load anaconda3/2020.11
conda activate wave_env_cl

# conda info

python3 run_automated_simulations_cluster.py $P_SET